FROM ruby:3.2.0-alpine3.17
LABEL maintainer="Gabriela Espirilla <gaby.es.sd@gmail.com>"

ENV APP_PATH /app
ENV BUNDLE_VERSION 2.4.1
ENV BUNDLE_PATH /usr/local/bundle/gems
ENV TMP_PATH /tmp/
ENV RAILS_LOG_TO_STDOUT true
ENV RAILS_PORT 3000

COPY ./entrypoints /entrypoints

RUN chmod -R +x /entrypoints \
    &&  apk -U add --no-cache \
        build-base \
        postgresql-dev \
        postgresql-client \
        musl-dev \
        libxml2-dev \
        libxslt-dev \
        nodejs \
    &&  rm -rf /var/cache/apk/* \
    &&  mkdir -p ${APP_PATH} \
    &&  gem install bundler --version "${BUNDLE_VERSION}" \
    &&  rm -rf $GEM_HOME/cache/*

WORKDIR ${APP_PATH}
COPY . ${APP_PATH}

EXPOSE ${RAILS_PORT}

ENV PATH="/entrypoints:$PATH"

ENTRYPOINT [ "bundle", "exec" ]